# Database Configuration
database:
  # SQL Server Configuration
  sqlserver:
    driver: "ODBC Driver 17 for SQL Server"
    server: "localhost"
    port: 1433
    database: "your_database_name"
    username: "your_username"
    password: "your_password"
    trusted_connection: false
    connection_timeout: 30
    
  # Alternative: PostgreSQL Configuration
  postgresql:
    host: "localhost"
    port: 5432
    database: "your_database_name"
    username: "your_username"
    password: "your_password"
    
  # Alternative: MySQL Configuration
  mysql:
    host: "localhost"
    port: 3306
    database: "your_database_name"
    username: "your_username"
    password: "your_password"

# LLM Configuration
llm:
  provider: "ollama"  # Options: ollama, openai, anthropic
  model: "llama3.1"   # For Ollama: llama3.1, codellama, mistral
  temperature: 0.1
  max_tokens: 4096
  base_url: "http://localhost:11434"  # Ollama default URL
  
# Embedding Configuration
embeddings:
  provider: "ollama"  # Options: ollama, sentence-transformers, openai
  model: "nomic-embed-text"  # For Ollama embedding model
  dimension: 768
  
# Vector Store Configuration
vectorstore:
  provider: "chroma"  # Options: chroma, faiss
  persist_directory: "./data/vectorstore"
  collection_name: "database_schema"
  
# RAG Configuration
rag:
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.7
  max_retrieved_docs: 5
  
# Application Settings
app:
  name: "RAG SQL Agent"
  version: "1.0.0"
  debug: true
  log_level: "INFO"
  max_query_history: 100
